language: python
dist: xenial
sudo: true
python:
  - 3.9


services:
  postgresql


env:
  global:
  - PIPENV_NO_INHERIT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install: 
  - pip install pipenv
  - pipenv sync --dev
  
before_script:
  - sudo systemctl restart postgresql
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=webdev --nomigrations
#Command to run tests
after_success:
  - pipenv run codecov
  
